/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://iqn5374gffg2xn6ocixytlv2ki.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-aoiatibzb5d4fn2hv6z4evpv5u",
    "aws_cognito_identity_pool_id": "us-west-2:7a892897-d453-4934-9fba-929472b98142",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_aHn76wXRE",
    "aws_user_pools_web_client_id": "1r2he25h2iocct75tpqdh74vha",
    "oauth": {},
    "predictions": {
        "convert": {
            "speechGenerator": {
                "region": "us-west-2",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Joanna",
                    "LanguageCode": "en-US"
                }
            }
        }
    }
};


export default awsmobile;
