/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c0b562b0-d727-4a64-9c09-933566792076",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_s5vDxgnWY",
    "aws_user_pools_web_client_id": "1k2jltsjoh7grncfm099ctmsev",
    "oauth": {},
    "predictions": {
        "convert": {
            "speechGenerator": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Joanna",
                    "LanguageCode": "en-US"
                }
            }
        }
    }
};


export default awsmobile;
