const options = {
  initialReportSize: [
    "dimension",
    "large",
    "medium",
    "mega",
    "small",
    "square feet",
    "square footage"
  ],
  initialReportHeight: [
    "2",
    "3",
    "high",
    "mid",
    "rise",
    "story",
    "single",
    "three",
    "two"
  ],
  initialReportOccupancy: [
    "apartment",
    "building",
    "business",
    "center",
    "commercial",
    "condo",
    "condominium",
    "duplex",
    "dwelling",
    "family",
    "garden",
    "hall",
    "high",
    "home",
    "house",
    "industrial",
    "medical",
    "mid",
    "multi",
    "office",
    "residential",
    "retail",
    "rise",
    "single",
    "taxpayer",
    "townhome",
    "town",
    "tiltup",
    "warehouse"
  ],
  initialReportConditions: ["fire", "nothing", "smoke", "showing"],
  initialReportActions: [
    "attack",
    "command",
    "entering",
    "establishing",
    "investigating",
    "investigation",
    "laying",
    "line",
    "lines",
    "mode",
    "quick",
    "rescue",
    "supply",
    "water"
  ],
  initialReportNeeds: [
    "2nd",
    "3rd",
    "alarm",
    "ambulance",
    "ems",
    "enforcement",
    "engine",
    "law",
    "officers",
    "pd",
    "police",
    "public works",
    "rescue",
    "second",
    "sheriff",
    "third",
    "truck"
  ],
  initialReportDesignation: ["command", "eye", "ic", "incident", "sea", "see"],
  threeSixtyConstruction: [
    "balloon",
    "clad",
    "concrete",
    "construction",
    "conventional",
    "cut",
    "frame",
    "light weight",
    "lightweight",
    "metal",
    "ordinary",
    "place",
    "poured",
    "stack",
    "stucco",
    "tilt up",
    "type",
    "vinyl",
    "wood"
  ],
  threeSixtyEntryEgress: ["alpha", "bravo", "charlie", "delta"],
  threeSixtyConditions: [
    "attic",
    "basement",
    "contents",
    "fire",
    "room",
    "structure"
  ],
  threeSixtyInteriorPath: [
    "alpha",
    "bidirectional",
    "bi-directional",
    "bravo",
    "charlie",
    "charley",
    "delta",
    "exhaust",
    "flow",
    "intake",
    "path",
    "unidirectional",
    "uni-directional"
  ],
  threeSixtySurvivability: [
    "survivability",
    "profile",
    "positive",
    "marginal",
    "negative"
  ],
  threeSixtyStrategicMode: ["defensive", "mode", "offensive", "transitional"],
  assignmentRescue: [
    "primary",
    "protect",
    "remove",
    "rescue",
    "search",
    "secondary"
  ],
  assignmentExposure: ["exposure", "extension", "eyes", "protect"],
  assignmentConfinement: [
    "attack",
    "check",
    "confinement",
    "hold",
    "limit",
    "restrain",
    "restrict"
  ],
  assignmentExtinguishment: [
    "attack",
    "hose",
    "interior",
    "line",
    "lines",
    "suppress",
    "suppression"
  ],
  assignmentOverhaul: ["hot", "overhaul", "spot"],
  assignmentVentilation: [
    "blower",
    "hole",
    "horizontal",
    "mechanical",
    "positive",
    "pressure",
    "roof",
    "ventilation",
    "vent",
    "vertical"
  ],
  assignmentSalvage: [
    "conservation",
    "covers",
    "property",
    "recovery",
    "salvage",
    "throw"
  ],
  incidentWithinIncident: ["incident"]
};

export { options };
