/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:651d3d89-8281-4251-821a-c7ea09dfc394",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_GDOT7q1VH",
    "aws_user_pools_web_client_id": "2l60fh8g3gia2t6drnc1ntqmpt",
    "oauth": {}
};


export default awsmobile;
