// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:f6b36abe-693b-4bd2-861f-b00e75f28e98",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_GuJsxiDEr",
    "aws_user_pools_web_client_id": "b4p6p8bc6jkncsl1ladr1m8n3",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://dbwdz5wo3zftdgpi3vwlcbmoky.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-mtbonvjvhzcwpm7v4znvvwmvsq",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://xfpbllz35e.execute-api.us-west-2.amazonaws.com/production",
            "region": "us-west-2"
        }
    ],
    "aws_content_delivery_bucket": "ctt-20200810122659-hostingbucket-production",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "https://d2cwjgrp9ql2xh.cloudfront.net",
    "predictions": {
        "convert": {
            "speechGenerator": {
                "region": "us-west-2",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Joanna",
                    "LanguageCode": "en-US"
                }
            },
            "transcription": {
                "region": "us-west-2",
                "proxy": false,
                "defaults": {
                    "language": "en-US"
                }
            }
        }
    }
};


export default awsmobile;
